export const PLAYER_STATUS_DISPLAY = {
  A: 'アクティブ',
  BRV: '忌引きリスト',
  D7: '7日間故障者リスト',
  D10: '10日間故障者リスト',
  D15: '15日間故障者リスト',
  D60: '60日間故障者リスト',
  DFA: 'DFA（戦力外）',
  FA: 'フリーエージェント',
  FME: '家族の医療緊急',
  LV: '有給休暇',
  MIN: 'マイナー降格',
  RM: 'マイナー降格',
  NRI: 'ノンロスター招待',
  PL: '父親休暇',
  RST: '制限リスト',
  RET: '引退',
  SUS: '出場停止',
  UDP: '未契約ドラフト指名',
  WV: 'ウェーバー',
  '': 'トレードまたは未登録',
} as const;

export const PLAYER_STATUS_PRIORITY = {
  A: 100,
  D7: 90,
  D10: 85,
  D15: 80,
  D60: 70,
  PL: 60,
  BRV: 55,
  FME: 50,
  LV: 45,
  RM: 42,
  MIN: 40,
  NRI: 30,
  DFA: 25,
  WV: 20,
  RST: 15,
  SUS: 10,
  FA: 5,
  RET: 3,
  UDP: 2,
  '': 0,
} as const;

