export const DIVISION_ID = {
  AMERICAN_EAST: 201,
  AMERICAN_CENTRAL: 202,
  AMERICAN_WEST: 200,
  NATIONAL_EAST: 204,
  NATIONAL_CENTRAL: 205,
  NATIONAL_WEST: 203,
} as const

export const DIVISION_NAME_JP = {
  [DIVISION_ID.AMERICAN_EAST]: "東地区",
  [DIVISION_ID.AMERICAN_CENTRAL]: "中地区",
  [DIVISION_ID.AMERICAN_WEST]: "西地区",
  [DIVISION_ID.NATIONAL_EAST]: "東地区",
  [DIVISION_ID.NATIONAL_CENTRAL]: "中地区",
  [DIVISION_ID.NATIONAL_WEST]: "西地区",
} as const

export const DIVISION_ABBR_JP = {
  [DIVISION_ID.AMERICAN_EAST]: "ア東",
  [DIVISION_ID.AMERICAN_CENTRAL]: "ア中",
  [DIVISION_ID.AMERICAN_WEST]: "ア西",
  [DIVISION_ID.NATIONAL_EAST]: "ナ東",
  [DIVISION_ID.NATIONAL_CENTRAL]: "ナ中",
  [DIVISION_ID.NATIONAL_WEST]: "ナ西",
} as const
