export const ERROR_CODE = {
  BAD_REQUEST: "BAD_REQUEST", // 400
  UNAUTHORIZED: "UNAUTHORIZED", // 401
  FORBIDDEN: "FORBIDDEN", // 403
  NOT_FOUND: "NOT_FOUND", // 404
  CONFLICT: "CONFLICT", // 409
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS", // 429
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR", // 500
  ERROR: "ERROR", // その他
} as const
