export const ERROR_CODE = {
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  ERROR: "ERROR", // その他
} as const

export const ERROR_CODE_TO_STATUS = {
  [ERROR_CODE.BAD_REQUEST]: 400,
  [ERROR_CODE.UNAUTHORIZED]: 401,
  [ERROR_CODE.FORBIDDEN]: 403,
  [ERROR_CODE.NOT_FOUND]: 404,
  [ERROR_CODE.CONFLICT]: 409,
  [ERROR_CODE.TOO_MANY_REQUESTS]: 429,
  [ERROR_CODE.INTERNAL_SERVER_ERROR]: 500,
  [ERROR_CODE.ERROR]: 500,
} as const
